In [1]:
import pandas as pd
import csv
import pandas_gbq
import time
from datetime import datetime
import os
from google.oauth2 import service_account
from google.cloud import bigquery
import re

In [2]:
CREDS = '../converge-database-0331482f2ee5.json'
client = bigquery.Client.from_service_account_json(json_credentials_path=CREDS)

In [63]:
seriatim = pd.DataFrame()
policy = pd.DataFrame()
notional = pd.DataFrame()
withdrawals = pd.DataFrame()
premiums = pd.DataFrame()
commissions = pd.DataFrame()
#set_month = '202301'

In [64]:
file_path = "I:New Structure/Actuarial New/Database/SILAC Settlements/2026/202603 Converge Teton Settlement file.xlsx"

In [65]:
seriatim = pd.read_excel(file_path, sheet_name='Seriatim')
withdrawals = pd.read_excel(file_path, sheet_name='Withdrawals')
premiums = pd.read_excel(file_path, sheet_name='Premiums')
notional = pd.read_excel(file_path, sheet_name='Notional')
commissions = pd.read_excel(file_path, sheet_name='Commissions')
deaths = pd.read_excel(file_path, sheet_name='Monthly Deaths')

In [66]:
credit_dictionary ={'Barclays Atlas 5 Point-to-Point PR' : 'ATLAS-AP2PPR', 'S&P 500 RavenPack AI Point-to-Point PR' : 'RVP-AP2PPR', 
                    'S&P 500 Monthly Average PR' : 'MAPR', 'S&P 500 Monthly Point-to-Point Cap': 'MP2PC', 'S&P 500 Point-to-Point Cap': 'AP2PC' ,
                    'S&P 500 Point-to-Point PR' : 'AP2PPR', 'NDX Generations 5 Point-to-Point PR': 'NASDAQ-AP2PPR', 'Barclays Atlas 5 Point-to-Point Spread' : 'ATLAS-AP2PS' ,
                   'Fixed Interest' : 'FI', 'NDX Generations 5 Point-to-Point Spread' : 'NASDAQ-AP2PS', 'S&P 500 RavenPack AI Point-to-Point Spread' : 'RVP-AP2PS' ,
                   'S&P 500 Monthly Average Cap' : 'MAC', 'S&P 500 Monthly Average Spread' : 'MAS',
                   'S&P 500 Duo Swift Point-to-Point PR' : 'SPDS-AP2PPR', 'CS RavenPack AI Point-to-Point PR' : 'RVP-AP2PPR', 'CS RavenPack AI Point-to-Point Spread': 'RVP-AP2PS',
                   'S&P 500 RavenPack AI Point-to-Point Sprd' : 'RVP-AP2PS'}

#Credit strategy changes every month

In [67]:
def clean_columns(df, *, space_replacement="", replace_parens=False):
    cols = (
        df.columns
        .str.strip()
        .str.lower()
        .map(lambda x: x.replace(" ", space_replacement))
    )
    
    if replace_parens:
        cols = (
            cols
            .map(lambda x: x.replace("(", "_"))
            .map(lambda x: x.replace(")", "_"))
        )
    
    df.columns = cols
    return df

In [68]:
seriatim = clean_columns(seriatim, space_replacement="_")
withdrawals = clean_columns(withdrawals, replace_parens=True)
premiums = clean_columns(premiums)
notional = clean_columns(notional)
commissions = clean_columns(commissions)
deaths = clean_columns(deaths)

In [69]:
seriatim['credit_id'] = seriatim['creditstrategy'].map(credit_dictionary)

In [70]:
#Getting columns only for the policy 
policy= seriatim.iloc[:,0:19]
# Add a new column named 'credit_id'
policy['credit_id'] = policy['creditstrategy'].map(credit_dictionary)
policy['creditstrategy'] = seriatim['creditstrategy']
policy.rider_spread = policy.rider_spread.astype("int64")

In [71]:
seriatim = seriatim.astype({"mtd_index_interest": "int",  "currentbonusrecoverypercentage" : "float", 
                            "strategy_ytd_nursing_care_withdrawals" : "float","strategy_ytd_home_health_care_withdrawals" : "float", 
                            "policy_ytd_cumulative_withdrawal": "int", "policy_ytd_nursing_care_withdrawals" : "int",
                            "policy_ytd_home_health_care_withdrawals":"float", "total_cumulative_withdrawal" : "int", 
                            "total_nursing_care_withdrawals" : "float", "total_home_health_care_withdrawals" : "float",
                            "strategy_ytd_terminal_illness_withdrawals" : "int", "strategy_ytd_cumulative_withdrawal" : "int", "policy_ytd_nursing_care_withdrawals": "float",
                           "total_terminal_illness_withdrawals" : "int" , "mtd_index_interest": "int","currentbonusrecoverypercentage" : "float",
                           "policy_ytd_terminal_illness_withdrawals" : "int"})

In [72]:
#Get the seriatim values after policy 
seriatim.drop(['product','plan', 'rateversion', 'stateofsale', 'taxqualstatus', 'issueyear', 'issuemonth', 'issueday',
              'issueage', 'ownerresidentstate', 'ownergender' ,'annuitant_issue_age', 'annuitant_gender',
              'joint_annuitant_issue_age', 'joint_annuitant_gender', 'riders', 'rider_spread'], axis=1, inplace=True, errors="ignore")
#seriatim.drop(['converge'], axis=1)
seriatim.rename(columns = {'joint/single_payment': 'joint_single_payment'}, inplace=True)
#premiums['deleteddate'] = pd.to_datetime(premiums['deleteddate'])

In [73]:
withdrawals = withdrawals.drop(['policyid','product', 'plan', 'approvaldate', 'policyissuestate' ], errors='ignore', axis=1)
premiums = premiums.drop(['policyid', 'product', 'approvaldate', 'policyissuestate','ownerissueage'], errors='ignore', axis=1)
notional = notional.drop(['polid','product_conf', 'rateversion', 'product', 'planlength', 'state','creditingstrategyname'], axis=1)
commissions = commissions.drop(['policyid','product','plan', 'approvaldate', 'policyissuestate'], errors='ignore', axis=1)
deaths = deaths.drop(['product', 'plan', 'withdrawaltype'],errors = 'ignore', axis=1)

In [74]:
withdrawals['totalpolicypremiumreceived'] = withdrawals['totalpolicypremiumreceived'].astype("float")
withdrawals['transactiondate'] = withdrawals['transactiondate'].astype("datetime64[ns]")

In [75]:
withdrawals = withdrawals.iloc[:, 0:36]

In [76]:
withdrawals = withdrawals.dropna(subset=['policynumber'], axis=0)

In [77]:
#get seriatim month from transaction date
get_seriatim_month = withdrawals['transactiondate'].apply(lambda x: x.strftime('%Y%m')) 
get_seriatim_month = get_seriatim_month[0]
get_seriatim_month

'202603'

In [78]:
product =policy["policynumber"].astype("str").str[0][0]+"%"

In [79]:
seriatim.rename(columns = {'converge_-_teton': 'converge'}, inplace=True)
withdrawals = withdrawals.drop(['converge-denali'], axis=1, errors="ignore")
commissions = commissions.drop(['converge-denali'], axis=1, errors="ignore")
premiums = premiums.drop(['converge-denali'], axis=1, errors="ignore")
notional = notional.drop(['converge-denali'], axis=1, errors="ignore")

### Header change codes here

In [80]:
seriatim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48805 entries, 0 to 48804
Data columns (total 64 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   policynumber                               48805 non-null  object
 1   creditstrategy                             48805 non-null  object
 2   optionbudget                               48805 non-null  float64
 3   totalinitpremium                           48805 non-null  float64
 4   totaladdlpremium                           48805 non-null  float64
 5   totalpolicypremiums                        48805 non-null  float64
 6   bonus_%                                    48805 non-null  float64
 7   totalinitprembonus                         48805 non-null  float64
 8   totaladdlprembonus                         48805 non-null  float64
 9   totalpolicypremiumbonus                    48805 non-null  float64
 10  totalpolicyiav                             48805 non-null  float64
 11  begcurrentyeartotalav                      48805 non-null  float64
 12  currentyearinitialallocation               48805 non-null  float64
 13  begcurrentyearcreditstrategyvalue          48805 non-null  float64
 14  strategyvalue                              48805 non-null  float64
 15  currentadjustment                          48805 non-null  float64
 16  currentyeareffectiveallocation             48805 non-null  float64
 17  totalpolicyav                              48805 non-null  float64
 18  totalpolicycv_beforemva                    48805 non-null  float64
 19  totalpolicymingtdvalue                     48805 non-null  float64
 20  totalpolicywc                              48805 non-null  float64
 21  totalbonusrecoveryamount                   48805 non-null  float64
 22  strategywc                                 48805 non-null  float64
 23  strategybonusrecoveryamount                48805 non-null  float64
 24  strategycv_beforemva                       48805 non-null  float64
 25  strategymingtdvalue                        48805 non-null  float64
 26  mtd_fixed_interest                         48805 non-null  float64
 27  mtd_index_interest                         48805 non-null  int32
 28  strategy_ytd_rmd                           48805 non-null  float64
 29  strategy_ytd_free_withdrawal               48805 non-null  float64
 30  strategy_ytd_cumulative_withdrawal         48805 non-null  int32
 31  strategy_ytd_other_withdrawals             48805 non-null  float64
 32  strategy_ytd_terminal_illness_withdrawals  48805 non-null  int32
 33  strategy_ytd_nursing_care_withdrawals      48805 non-null  float64
 34  strategy_ytd_home_health_care_withdrawals  48805 non-null  float64
 35  strategy_ytd_partial_freelook              48805 non-null  int64
 36  policy_ytd_rmd                             48805 non-null  float64
 37  policy_ytd_free_withdrawal                 48805 non-null  float64
 38  policy_ytd_cumulative_withdrawal           48805 non-null  int32
 39  policy_ytd_other_withdrawals               48805 non-null  float64
 40  policy_ytd_terminal_illness_withdrawals    48805 non-null  int32
 41  policy_ytd_nursing_care_withdrawals        48805 non-null  float64
 42  policy_ytd_home_health_care_withdrawals    48805 non-null  float64
 43  policy_ytd_partial_freelook                48805 non-null  int64
 44  total_rmd                                  48805 non-null  float64
 45  total_free_withdrawal                      48805 non-null  float64
 46  total_cumulative_withdrawal                48805 non-null  int32
 47  total_other_withdrawals                    48805 non-null  float64
 48  total_terminal_illness_withdrawals         48805 non-null  int32
 49  total_nursing_care_withdrawals             48805 non-null  float64
 50  total_home_health_care_withdrawals         48805 non-null  float64
 51  total_partial_freelook                     48805 non-null  float64
 52  firateminadj                               48805 non-null  float64
 53  freewithdrawalavailable                    48805 non-null  float64
 54  initialwithdrawalcharge                    48805 non-null  float64
 55  currentwithdrawalcharge                    48805 non-null  float64
 56  currentbonusrecoverypercentage             48805 non-null  float64
 57  mgv_premium                                48805 non-null  float64
 58  mgv_fixed                                  48805 non-null  float64
 59  mgv_index                                  48805 non-null  float64
 60  reinsurancecode                            48805 non-null  object
 61  reserves2                                  48805 non-null  float64
 62  converge                                   48805 non-null  float64
 63  credit_id                                  48256 non-null  object
dtypes: float64(51), int32(7), int64(2), object(4)
memory usage: 22.5+ MB

In [81]:
seriatim.rename(columns = {"payout/lifetime_withdrawal_type" : "joint_single_payment", "lifetimelevsingle50" : "lifetimesingle50", "lifetimelevsingle60" : "lifetimesingle60", 
                           "lifetimelevsingle70" : "lifetimesingle70", "lifetimelevsingle80" : "lifetimesingle80", 
                           "lifetimelevjoint50" : "lifetimejoint50", "lifetimelevjoint60" : "lifetimejoint60", "lifetimelevjoint70" : "lifetimejoint70", "lifetimelevjoint80" : "lifetimejoint80"
                          ,"total_premium_bonus_%": "total_premium_bonus_percent", "lifetime_withdrawals_elected_date" : "lifetimewithdrawalselecteddate", 
                           "wellness_withdrawals_elected_date": "wellnesswithdrawalselecteddate", "wellness_withdrawals_termination_date" :"wellnesswithdrawalstermdate"}, inplace=True)

In [82]:
if product =='D%':
    seriatim = seriatim.astype({"lifetimewithdrawalselecteddate" : "datetime64[ns]", "wellnesswithdrawalselecteddate" : "datetime64[ns]", "wellnesswithdrawalstermdate" : "datetime64[ns]" })

In [83]:
def to_upload (data, table_name,get_seriatim_month):
    df = pd.DataFrame()    
    df = data
    if table_name not in ("premiums", "commissions", "notional"):
        df['set_month'] = get_seriatim_month 
    print('start pushing policy data')
    start = time.time()
    df.to_gbq("converge-database.denali."+table_name,
                 if_exists='append',
                 project_id="converge-database") 
    end = time.time()
    logs(get_seriatim_month, file_path, str(table_name))
    print("time took to upload " + str(end - start))
    print('success')

In [84]:
def logs(get_seriatim_month, file_path, sheetname):
    log = pd.DataFrame()
    #creating logs and the timestamp in it. 
    log['time'] = [pd.Timestamp(datetime.now())]
    log['file'] = file_path
    log['sheetname']=sheetname
    log.to_gbq("converge-database.denali.logs",
                   if_exists='append',
                   project_id="converge-database")

In [85]:
policy

,policynumber,product,plan,riders,rider_spread,rateversion,creditstrategy,stateofsale,taxqualstatus,issueyear,issuemonth,issueday,issueage,ownerresidentstate,ownergender,annuitant_issue_age,annuitant_gender,joint_annuitant_issue_age,joint_annuitant_gender,credit_id
0,T000004959,Teton,10,Not Applicable (N/A),0,8.70,Fixed Interest,PA,IRA,2020,12,30,55,PA,Female,55,Female,NaN,NaN,FI
1,T000004959,Teton,10,Not Applicable (N/A),0,8.70,S&P 500 Point-to-Point Cap,PA,IRA,2020,12,30,55,PA,Female,55,Female,NaN,NaN,AP2PC
2,T000005010,Teton,10,Not Applicable (N/A),0,9.90,S&P 500 Monthly Average PR,GA,IRA,2021,3,10,46,GA,Female,46,Female,NaN,NaN,MAPR
3,T000005010,Teton,10,Not Applicable (N/A),0,9.90,Barclays Atlas 5 Point-to-Point PR,GA,IRA,2021,3,10,46,GA,Female,46,Female,NaN,NaN,ATLAS-AP2PPR
4,T000005100,Teton,7,Not Applicable (N/A),0,8.70,S&P 500 Point-to-Point PR,CT,Non-Qualified,2020,12,23,66,CT,Female,66,Female,NaN,NaN,AP2PPR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48800,TB00055502,Teton Bonus,14,Not Applicable (N/A),0,12.18,S&P 500 Point-to-Point Cap,GA,Non-Qualified,2022,12,21,51,GA,Male,51,Male,NaN,NaN,AP2PC
48801,TB00055504,Teton Bonus,14,Not Applicable (N/A),0,12.18,NDX Generations 5 Point-to-Point PR,GA,Non-Qualified,2022,12,21,48,FL,Female,48,Female,NaN,NaN,NASDAQ-AP2PPR
48802,TB00055504,Teton Bonus,14,Not Applicable (N/A),0,12.18,Barclays Atlas 5 Point-to-Point PR,GA,Non-Qualified,2022,12,21,48,FL,Female,48,Female,NaN,NaN,ATLAS-AP2PPR
48803,TB00067493,Teton Bonus,14,Not Applicable (N/A),0,9.80,Barclays Atlas 5 Point-to-Point PR,TN,IRA,2021,3,3,59,TN,Male,59,Male,NaN,NaN,ATLAS-AP2PPR
48804,TB00067494,Teton Bonus,14,Not Applicable (N/A),0,9.80,Barclays Atlas 5 Point-to-Point PR,TN,IRA,2021,3,3,53,IN,Female,53,Female,NaN,NaN,ATLAS-AP2PPR

In [86]:
to_upload(policy,"policy",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 3.966109037399292
success

In [87]:
seriatim = seriatim.iloc[:, 0:87]

In [88]:
seriatim

,policynumber,creditstrategy,optionbudget,totalinitpremium,totaladdlpremium,totalpolicypremiums,bonus_%,totalinitprembonus,totaladdlprembonus,totalpolicypremiumbonus,...,initialwithdrawalcharge,currentwithdrawalcharge,currentbonusrecoverypercentage,mgv_premium,mgv_fixed,mgv_index,reinsurancecode,reserves2,converge,credit_id
0,T000004959,Fixed Interest,0.0225,66434.52,0.45,66434.97,0.0,0.0,0.0,0.0,...,0.0930,0.0475,0.0,0.875,0.0100,0.01,AG,34445.750000,0.10,FI
1,T000004959,S&P 500 Point-to-Point Cap,0.0225,66434.52,0.45,66434.97,0.0,0.0,0.0,0.0,...,0.0930,0.0475,0.0,0.875,0.0100,0.01,AG,34259.695312,0.10,AP2PC
2,T000005010,S&P 500 Monthly Average PR,0.0265,49442.07,0.00,49442.07,0.0,0.0,0.0,0.0,...,0.1200,0.0800,0.0,0.875,0.0100,0.01,AJ,10795.020508,0.10,MAPR
3,T000005010,Barclays Atlas 5 Point-to-Point PR,0.0265,49442.07,0.00,49442.07,0.0,0.0,0.0,0.0,...,0.1200,0.0800,0.0,0.875,0.0100,0.01,AJ,43180.082031,0.10,ATLAS-AP2PPR
4,T000005100,S&P 500 Point-to-Point PR,0.0231,400000.00,200000.00,600000.00,0.0,0.0,0.0,0.0,...,0.1250,0.0800,0.0,0.875,0.0100,0.01,AC,654223.625000,0.10,AP2PPR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48800,TB00055502,S&P 500 Point-to-Point Cap,0.0335,105000.00,0.00,105000.00,0.1,10500.0,0.0,10500.0,...,0.1475,0.1175,1.0,0.875,0.0175,0.01,AHZ,55533.386719,0.15,AP2PC
48801,TB00055504,NDX Generations 5 Point-to-Point PR,0.0335,105000.00,0.00,105000.00,0.1,10500.0,0.0,10500.0,...,0.1475,0.1175,1.0,0.875,0.0175,0.01,AHZ,54168.847656,0.15,NASDAQ-AP2PPR
48802,TB00055504,Barclays Atlas 5 Point-to-Point PR,0.0335,105000.00,0.00,105000.00,0.1,10500.0,0.0,10500.0,...,0.1475,0.1175,1.0,0.875,0.0175,0.01,AHZ,54168.847656,0.15,ATLAS-AP2PPR
48803,TB00067493,Barclays Atlas 5 Point-to-Point PR,0.0228,32795.01,0.00,32795.01,0.1,3279.5,0.0,3279.5,...,0.1475,0.1000,1.0,0.875,0.0100,0.01,AAI,34968.125000,0.10,ATLAS-AP2PPR
48804,TB00067494,Barclays Atlas 5 Point-to-Point PR,0.0228,32795.00,0.00,32795.00,0.1,3279.5,0.0,3279.5,...,0.1475,0.1000,1.0,0.875,0.0100,0.01,AAI,34892.742188,0.10,ATLAS-AP2PPR

In [89]:
to_upload(seriatim,"seriatim_values",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<00:00, 64.20it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 5.902164936065674
success

In [90]:
notional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13497 entries, 0 to 13496
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   policynumber            13497 non-null  object
 1   optionbudget            13497 non-null  float64
 2   issuedate               13497 non-null  datetime64[ns]
 3   rider                   13497 non-null  object
 4   reinsurancecode         13497 non-null  object
 5   transactiondescription  13497 non-null  object
 6   initallocamount         13497 non-null  int64
 7   reallocamount           13497 non-null  int64
 8   trandate                13497 non-null  datetime64[ns]
 9   creditingstrategy       13497 non-null  object
 10  adjustment              13497 non-null  float64
 11  converge                13497 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(5)
memory usage: 1.2+ MB

In [91]:
notional = notional.dropna(subset=['policynumber'], axis=0)

In [92]:
notional = notional.iloc[:,0:12]

In [93]:
to_upload(notional,"notional",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 5.6721765995025635
success

In [94]:
withdrawals = withdrawals.astype({"termdate" : "datetime64[ns]"})

In [95]:
to_upload(withdrawals,"withdrawals",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 5.204579591751099
success

In [96]:
premiums = premiums.dropna(subset=['policynumber'], axis=0)

In [97]:
premiums = premiums.iloc[:,0:17]

In [98]:
premiums['premiumrecognitionyyyymm']= premiums['premiumrecognitionyyyymm'].astype("int64")

In [99]:
premiums['terminateddate'] =premiums['terminateddate'].astype('datetime64[s]')
premiums['addtlpremrcvddate'] =premiums['addtlpremrcvddate'].astype('datetime64[s]')
premiums['deleteddate'] =premiums['deleteddate'].astype('datetime64[s]')
premiums['premiumrecognitionmonth'] =premiums['premiumrecognitionmonth'].astype('datetime64[s]')
premiums['plan'] = premiums['plan'].astype("string")

In [100]:
to_upload(premiums,"premiums",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 4.66284441947937
success

In [101]:
commissions

,policynumber,rider,reinsurancecode,issuedate,enterdate,description,agentnumber,premiumamount,commpercent,commissionamount,commissionrecognitionmonth,commissionrecognitionyyyymm,converge
0,TB00017522,None,AAJ,2021-04-14,2026-03-30,Commission Schedule changed because of age change,317660,-9194.15,0.020,-183.88,2026-03-30,202603,0.1
1,TB00017522,None,AAJ,2021-04-14,2026-03-30,Commission Schedule changed because of age change,1280460,-9194.15,0.095,-873.44,2026-03-30,202603,0.1
2,TB00017522,None,AAJ,2021-04-14,2026-03-30,Commission Earned,317660,9194.15,0.030,275.82,2026-03-30,202603,0.1
3,TB00017522,None,AAJ,2021-04-14,2026-03-30,Commission Earned,1280460,9194.15,0.090,827.47,2026-03-30,202603,0.1
4,TB00029653,None,AFR,2022-02-02,2026-03-10,Charge Back - Free Look,1400800,-70200.00,0.025,-1755.00,2026-03-10,202603,0.3
5,TB00029653,None,AFR,2022-02-02,2026-03-10,Charge Back - Free Look,1401770,-70200.00,0.085,-5967.00,2026-03-10,202603,0.3
6,TB00029653,None,AFR,2022-02-02,2026-03-10,Charge Back - Free Look,1225710,-70200.00,0.005,-351.00,2026-03-10,202603,0.3
7,TB00036634,None,AIQ,2023-03-15,2026-03-28,Additional Commission Earned,1265970,2995.16,0.061,182.70,2026-03-28,202603,0.1
8,TB00036634,None,AIQ,2023-03-15,2026-03-28,Additional Commission Earned,1221010,2995.16,0.004,11.98,2026-03-28,202603,0.1
9,TB00036634,None,AIQ,2023-03-15,2026-03-24,Additional Commission Earned,1265970,2203.63,0.061,134.42,2026-03-24,202603,0.1
10,TB00036634,None,AIQ,2023-03-15,2026-03-24,Additional Commission Earned,1221010,2203.63,0.004,8.81,2026-03-24,202603,0.1
11,TB00036634,None,AIQ,2023-03-15,2026-03-19,Additional Commission Earned,1265970,3228.58,0.061,196.94,2026-03-19,202603,0.1
12,TB00036634,None,AIQ,2023-03-15,2026-03-19,Additional Commission Earned,1221010,3228.58,0.004,12.91,2026-03-19,202603,0.1
13,TB00037197,None,AIW,2023-04-19,2026-03-23,Charge Back - Free Look,317740,-20204.98,0.016,-323.28,2026-03-23,202603,0.1
14,TB00037197,None,AIW,2023-04-19,2026-03-23,Charge Back - Free Look,1263630,-20204.98,0.049,-990.04,2026-03-23,202603,0.1

In [102]:
commissions = commissions.iloc[:,0:13]

In [103]:
commissions = commissions.dropna(subset=['policynumber'],axis=0)

In [ ]:
#commissions.rename(columns={"policyid": "policynumber"}, inplace=True)

In [104]:
commissions['commissionrecognitionyyyymm'] = commissions['commissionrecognitionyyyymm'].astype("int64")

In [105]:
commissions['issuedate'] = commissions['issuedate'].astype("datetime64[ns]")
commissions['agentnumber'] = commissions['agentnumber'].astype("int64")
commissions['enterdate'] = commissions['enterdate'].astype("datetime64[ns]")
commissions['commissionrecognitionmonth'] = commissions['commissionrecognitionmonth'].astype("datetime64[ns]")

In [106]:
commissions = commissions.drop(['rider'], axis=1)

In [107]:
to_upload(commissions,"commissions",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 3.775377035140991
success

In [108]:
deaths

   policynumber rider   termdate reinsurancecode    totaldeath  converge
0    T000005790  None 2026-03-12              AC  1.076821e+05      0.10
1    T000006715  None 2026-03-25              AC  2.948679e+04      0.10
2    T000007200  None 2026-03-19              AC  5.024441e+04      0.10
3    T000007288  None 2026-03-03              AD  1.002593e+05      0.10
4    T000007610  None 2026-03-26             AAL  3.630612e+04      0.10
5    T000009627  None 2026-03-31             ACB  2.868214e+05      0.30
6    T000009878  None 2026-03-30             AFM  4.069087e+04      0.30
7    T000005789  None 2026-03-12              AC  3.292593e+05      0.10
8    T000011520  None 2026-03-31             AHI  2.315594e+04      0.10
9    T000006505  None 2026-03-27              AC  3.036949e+04      0.10
10   T000008167  None 2026-03-05             AAY  1.000053e+05      0.10
11   T000009684  None 2026-03-25             AFH  2.004514e+06      0.30
12   T000010121  None 2026-03-04             AFT  2.166418e+05      0.30
13   T000010122  None 2026-03-04             AFT  2.094014e+05      0.30
14   TB00017238  None 2026-03-19              AY  8.254142e+04      0.10
15   TB00018370  None 2026-03-12              AY  2.559653e+04      0.10
16   TB00019061  None 2026-03-24              AU  9.825266e+04      0.10
17   TB00024745  None 2026-03-03             AAU  6.857484e+04      0.10
18   TB00027040  None 2026-03-23             ABO  8.963142e+04      0.30
19   TB00027482  None 2026-03-09             ABY  1.390961e+04      0.30
20   TB00017747  None 2026-03-25              AY  1.244251e+05      0.10
21   TB00028489  None 2026-03-24             ABX  6.065340e+04      0.30
22   TB00028672  None 2026-03-23             ABY  1.182176e+05      0.30
23   TB00019333  None 2026-03-06              AY  2.394988e+04      0.10
24   TB00028774  None 2026-03-31             ACE  4.387761e+04      0.30
25   TB00020054  None 2026-03-12              AU  2.187639e+04      0.10
26   TB00030144  None 2026-03-31             AFR  6.135405e+04      0.30
27   TB00020539  None 2026-03-26              AZ  3.470639e+04      0.10
28   TB00030580  None 2026-03-30             AFW  1.761129e+05      0.30
29   TB00021096  None 2026-03-18             AAA  6.556961e+04      0.10
30   TB00021721  None 2026-03-30              AU  1.899493e+04      0.10
31   TB00032031  None 2026-03-31             AGO  1.567300e+05      0.30
32   TB00021988  None 2026-03-12             AAI  2.419476e+04      0.10
33   TB00032700  None 2026-03-12             AGT  1.417911e+06      0.30
34   TB00023573  None 2026-03-30             AAO  1.725261e+04      0.10
35   TB00032794  None 2026-03-12             AGO  1.247018e+04      0.30
36   TB00024961  None 2026-03-17             AAW  5.894575e+04      0.10
37   TB00032795  None 2026-03-12             AGO  7.140259e+04      0.30
38   TB00033612  None 2026-03-23             AGZ  2.644773e+05      0.46
39   TB00034156  None 2026-03-24             AHA  2.333168e+05      0.46
40   TB00035016  None 2026-03-20             AIE  1.228925e+05      0.15
41   TB00024965  None 2026-03-13             ABG  1.863209e+04      0.25
42   TB00027153  None 2026-03-31             ABI  2.503238e+05      0.25
43   TB00037246  None 2026-03-18             AJB  3.233405e+04      0.05
44   TB00037330  None 2026-03-09             AIW  6.448976e+04      0.10
45   TB00037334  None 2026-03-09             AIW  6.178990e+04      0.10
46   TB00030020  None 2026-03-30             AFP  5.800334e+04      0.30
47   TB00030301  None 2026-03-18             AFQ  6.593661e+04      0.30
48   TB00030393  None 2026-03-20             AFP  2.404845e+04      0.30
49   TB00030414  None 2026-03-16             AFQ  4.196168e+05      0.30
50   TB00031864  None 2026-03-10             AGP  1.621212e+04      0.30
51   TB00032559  None 2026-03-12             AGO  2.265026e+05      0.30
52   TB00033126  None 2026-03-31             AGU  7.386432e+04      0.30
53   TB00034647  None 2026-03-18             AHN  1.908203e+05      0.10
54   TB00037029  None 2026-03-09             AIP  1.148521e+04      0.10
55   TB00037289  None 2026-03-30             AIP  3.545683e+04      0.10

In [109]:
deaths = deaths.rename(columns ={"reinsurancecode" : "reins"})

In [110]:
deaths['converge'] = deaths['converge'].astype("float64")
deaths['reins'] = deaths['reins'].astype("string")

In [111]:
deaths = deaths.iloc[:,0:5]

In [112]:
deaths = deaths.dropna(subset=['policynumber'],axis=0)

In [113]:
deaths = deaths.drop(['rider'], axis=1)

In [114]:
to_upload(deaths,"deaths",get_seriatim_month)

start pushing policy data

100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

time took to upload 3.7736759185791016
success

In [115]:
df_test = pd.DataFrame()

In [116]:
#Testing
def test(table, set_month, product):
    print('Startin the Test for', set_month)
    #product teton or denali 
    df = pd.DataFrame()
    if 'Teton' in product:
        product = 'T%'
    elif 'Denali' in product:
        product = 'D%'
    print('And Product  =', product)
    
    print('Table Name: ', table)
    print('Query running: ')
    if table == 'policy':    
        query = 'SELECT count(*) from `denali.policy` WHERE set_month="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result=policy.policynumber.count()
    elif table =='seriatim':
        query = 'SELECT sum(reserves2) from `denali.seriatim_values` WHERE set_month="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result=seriatim.reserves2.sum()
    elif table == 'premiums':
        query = 'SELECT sum(totaladdtlpremium) from `denali.premiums` WHERE CAST(premiumrecognitionyyyymm as STRING)="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result=premiums.totaladdtlpremium.sum()
    elif table == 'withdrawals':
        query = 'SELECT sum(fullsurrenders) from `denali.withdrawals` WHERE set_month="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result = withdrawals.fullsurrenders.sum()
    elif table == 'notional':
        query = 'SELECT sum(reallocamount) from `denali.notional` WHERE FORMAT_TIMESTAMP("%Y%m", trandate)="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result = notional.reallocamount.sum()
    elif table == 'commissions':
        query = 'SELECT sum(commissionamount) from `denali.commissions` WHERE CAST(commissionrecognitionyyyymm as STRING)="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result = commissions.commissionamount.sum()
    elif table == 'deaths':
        query = 'SELECT sum(totaldeath) from `denali.deaths` WHERE set_month="'+set_month+'" AND policynumber like "'+product+'"'
        excel_result = deaths.totaldeath.sum()
    print(query)
    job = client.query(query)  
    for i in job.result():
        result = i[0]
        
    #Comparing with the Excel file

    print(type(result))
    print(type(excel_result))
    print('starts check here')
   
    if round(float(result),2) == round(float(excel_result), 2):
        print("Database Result: ", round(float(result),2))
        print("Excel Result: ", round(float(excel_result),2))
        test_result = 'Pass'
    else:
        print("Database Result: ", result)
        print("Excel Result: ", excel_result)
        test_result = 'Fail'
    print(test_result)
    print('-----------------')
    return test_result

In [117]:
test_fields = ['policy', 'seriatim', 'premiums', 'withdrawals', 'notional', 'commissions', 'deaths']

for i in test_fields:
    test(i, get_seriatim_month, file_path)

Startin the Test for 202603
And Product  = T%
Table Name:  policy
Query running:
SELECT count(*) from `denali.policy` WHERE set_month="202603" AND policynumber like "T%"
<class 'int'>
<class 'numpy.int64'>
starts check here
Database Result:  48805.0
Excel Result:  48805.0
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  seriatim
Query running:
SELECT sum(reserves2) from `denali.seriatim_values` WHERE set_month="202603" AND policynumber like "T%"
<class 'float'>
<class 'numpy.float64'>
starts check here
Database Result:  1833565397.94
Excel Result:  1833565397.94
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  premiums
Query running:
SELECT sum(totaladdtlpremium) from `denali.premiums` WHERE CAST(premiumrecognitionyyyymm as STRING)="202603" AND policynumber like "T%"
<class 'float'>
<class 'numpy.float64'>
starts check here
Database Result:  -1610420.07
Excel Result:  -1610420.07
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  withdrawals
Query running:
SELECT sum(fullsurrenders) from `denali.withdrawals` WHERE set_month="202603" AND policynumber like "T%"
<class 'float'>
<class 'numpy.float64'>
starts check here
Database Result:  10102137.38
Excel Result:  10102137.38
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  notional
Query running:
SELECT sum(reallocamount) from `denali.notional` WHERE FORMAT_TIMESTAMP("%Y%m", trandate)="202603" AND policynumber like "T%"
<class 'int'>
<class 'numpy.int64'>
starts check here
Database Result:  208251501.0
Excel Result:  208251501.0
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  commissions
Query running:
SELECT sum(commissionamount) from `denali.commissions` WHERE CAST(commissionrecognitionyyyymm as STRING)="202603" AND policynumber like "T%"
<class 'float'>
<class 'numpy.float64'>
starts check here
Database Result:  -8792.59
Excel Result:  -8792.59
Pass
-----------------
Startin the Test for 202603
And Product  = T%
Table Name:  deaths
Query running:
SELECT sum(totaldeath) from `denali.deaths` WHERE set_month="202603" AND policynumber like "T%"
<class 'float'>
<class 'numpy.float64'>
starts check here
Database Result:  8622192.39
Excel Result:  8622192.39
Pass
-----------------

In [118]:
set_month = get_seriatim_month
import sys

In [119]:
#Importing AVRF analysis


sys.path.append('avrf_analysis_silac.py')
import avrf_analysis_silac
# Trigger the AVRF analysis

In [120]:
avrf_analysis_silac.run_avrf_analysis(set_month, product)

check set_month value: 202603
BigQuery client initialized successfully!
Running AVRF analysis for set_month:
 202603 T%
difference is more then threshold amount:
AVRF result exported and Complete

In [121]:
query_report = f'''
UPDATE `denali.policy` p1
SET p1.reported_date = (SELECT MIN(p2.set_month) from `denali.policy` p2 WHERE p2.policynumber = p1.policynumber)
WHERE p1.reported_date IS NULL
'''
job = client.query(query_report)

### Run this After the upload for Both Denali and Teton

In [123]:
sys.path.append('../actuarial-pipelines/reconciliations/silac/')
from reconciliation import run_reconciliation
run_reconciliation(set_month)

Starting the program

Running reconciliation for SILAC 202603
SELECT CAST(sum(w.internalreissues*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as internalreissues_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'internalreissues', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.fullsurrenders*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as fullsurrenders_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'fullsurrenders', 'total': 2643287}
-----------------------------------------------
SELECT CAST(sum(w.partialwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as partialwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'partialwithdrawals', 'total': 1017021}
-----------------------------------------------
SELECT CAST(sum(w.cancellationamount*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as cancellationamount_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'cancellationamount', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.rmdwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as rmdwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'rmdwithdrawals', 'total': 335359}
-----------------------------------------------
SELECT CAST(sum(w.otherwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as otherwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'otherwithdrawals', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.lifetimewithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as lifetimewithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'lifetimewithdrawals', 'total': 246238}
-----------------------------------------------
SELECT CAST(sum(w.homecare*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as homecare_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'homecare', 'total': 4277}
-----------------------------------------------
SELECT CAST(sum(w.nursinghome*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as nursinghome_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'nursinghome', 'total': 66387}
-----------------------------------------------
SELECT CAST(sum(w.terminalillness*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as terminalillness_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'terminalillness', 'total': 51179}
-----------------------------------------------
SELECT CAST(sum(w.wellnesswithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as wellnesswithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'wellnesswithdrawals', 'total': 2813}
-----------------------------------------------
SELECT CAST(sum(w.surrendercharges_includesmvaandbonusrecapture_*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as surrendercharges_includesmvaandbonusrecapture__sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'surrendercharges_includesmvaandbonusrecapture_', 'total': -610875}
-----------------------------------------------
SELECT CAST(sum(w.premiumtaxes*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as premiumtaxes_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'premiumtaxes', 'total': 0}
-----------------------------------------------
WITH initial_prem AS (  SELECT pm.policynumber as policynumber, pm.totalinitpremium*(SELECT max(sv.converge) from `denali.seriatim_values` sv WHERE sv.policynumber = pm.policynumber) as gross_intial, from `denali.premiums` pm  where pm.premiumrecognitionyyyymm = CAST(202603 AS INT64) and pm.policynumber like "D%" and pm.substatus is NULL and pm.totalinitpremium IS NOT NULL)   SELECT SUM(gross_intial) from initial_prem
{'product': 'Denali', 'fieldname': 'gross_initial_premium', 'total': 0.0}
WITH addtl_prem AS (  SELECT pm.policynumber as policynumber, pm.totaladdtlpremium*(SELECT max(sv.converge) from `denali.seriatim_values` sv WHERE sv.policynumber = pm.policynumber) as gross_intial, from `denali.premiums` pm  where pm.premiumrecognitionyyyymm = CAST(202603 AS INT64) and pm.policynumber like "D%" and pm.substatus is NULL and pm.totaladdtlpremium IS NOT NULL)   SELECT SUM(gross_intial) from addtl_prem
{'product': 'Denali', 'fieldname': 'gross_addtl_premium', 'total': 1659.9705}
SELECT CAST(sum(d.totaldeath*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = d.policynumber group by d.policynumber) ) as INT) as death_sum  FROM `denali.deaths` d WHERE set_month = "202603" AND d.policynumber LIKE "D%"
{'product': 'Denali', 'fieldname': 'death', 'total': 1202279}
{'product': 'Denali', 'fieldname': 'initial_commission_paid', 'total': 6568.315}
{'product': 'Denali', 'fieldname': 'commission_recovered', 'total': -443.736}
-----------------------------------------------
SELECT CAST(sum(w.internalreissues*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as internalreissues_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'internalreissues', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.fullsurrenders*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as fullsurrenders_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'fullsurrenders', 'total': 2151146}
-----------------------------------------------
SELECT CAST(sum(w.partialwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as partialwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'partialwithdrawals', 'total': 1082416}
-----------------------------------------------
SELECT CAST(sum(w.cancellationamount*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as cancellationamount_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'cancellationamount', 'total': 23080}
-----------------------------------------------
SELECT CAST(sum(w.rmdwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as rmdwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'rmdwithdrawals', 'total': 320675}
-----------------------------------------------
SELECT CAST(sum(w.otherwithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as otherwithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'otherwithdrawals', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.lifetimewithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as lifetimewithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'lifetimewithdrawals', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.homecare*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as homecare_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'homecare', 'total': 1788}
-----------------------------------------------
SELECT CAST(sum(w.nursinghome*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as nursinghome_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'nursinghome', 'total': 51432}
-----------------------------------------------
SELECT CAST(sum(w.terminalillness*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as terminalillness_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'terminalillness', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.wellnesswithdrawals*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as wellnesswithdrawals_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'wellnesswithdrawals', 'total': 0}
-----------------------------------------------
SELECT CAST(sum(w.surrendercharges_includesmvaandbonusrecapture_*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as surrendercharges_includesmvaandbonusrecapture__sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'surrendercharges_includesmvaandbonusrecapture_', 'total': -371839}
-----------------------------------------------
SELECT CAST(sum(w.premiumtaxes*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = w.policynumber group by w.policynumber) ) as INT) as premiumtaxes_sum  FROM `denali.withdrawals` w WHERE set_month = "202603" AND w.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'premiumtaxes', 'total': 0}
-----------------------------------------------
WITH initial_prem AS (  SELECT pm.policynumber as policynumber, pm.totalinitpremium*(SELECT max(sv.converge) from `denali.seriatim_values` sv WHERE sv.policynumber = pm.policynumber) as gross_intial, from `denali.premiums` pm  where pm.premiumrecognitionyyyymm = CAST(202603 AS INT64) and pm.policynumber like "T%" and pm.substatus is NULL and pm.totalinitpremium IS NOT NULL)   SELECT SUM(gross_intial) from initial_prem
{'product': 'Teton', 'fieldname': 'gross_initial_premium', 'total': 0.0}
WITH addtl_prem AS (  SELECT pm.policynumber as policynumber, pm.totaladdtlpremium*(SELECT max(sv.converge) from `denali.seriatim_values` sv WHERE sv.policynumber = pm.policynumber) as gross_intial, from `denali.premiums` pm  where pm.premiumrecognitionyyyymm = CAST(202603 AS INT64) and pm.policynumber like "T%" and pm.substatus is NULL and pm.totaladdtlpremium IS NOT NULL)   SELECT SUM(gross_intial) from addtl_prem
{'product': 'Teton', 'fieldname': 'gross_addtl_premium', 'total': 842.7370000000001}
SELECT CAST(sum(d.totaldeath*(SELECT max(sv.converge) FROM `denali.seriatim_values` AS sv   WHERE sv.policynumber = d.policynumber group by d.policynumber) ) as INT) as death_sum  FROM `denali.deaths` d WHERE set_month = "202603" AND d.policynumber LIKE "T%"
{'product': 'Teton', 'fieldname': 'death', 'total': 2259201}
{'product': 'Teton', 'fieldname': 'initial_commission_paid', 'total': 165.10500000000002}
{'product': 'Teton', 'fieldname': 'commission_recovered', 'total': -2658.964}
-----------------------------------------------
end

   product                                          fieldname           total
0   Denali                                   internalreissues               0
1   Denali                                     fullsurrenders         2643287
2   Denali                                 partialwithdrawals         1017021
3   Denali                                 cancellationamount               0
4   Denali                                     rmdwithdrawals          335359
5   Denali                                   otherwithdrawals               0
6   Denali                                lifetimewithdrawals          246238
7   Denali                                           homecare            4277
8   Denali                                        nursinghome           66387
9   Denali                                    terminalillness           51179
10  Denali                                wellnesswithdrawals            2813
11  Denali     surrendercharges_includesmvaandbonusrecapture_         -610875
12  Denali                                       premiumtaxes               0
13  Denali                              gross_initial_premium             0.0
14  Denali                                gross_addtl_premium       1659.9705
15  Denali                                              death         1202279
16  Denali                            initial_commission_paid        6568.315
17  Denali                               commission_recovered        -443.736
18  Denali                      number_of_contract_issued_acq               2
19  Denali  acq_expense ($100 per policy x #contracts issued)             8.0
20  Denali                                  maintance_expense    24019.123154
21  Denali                                        hedgin_cost  1077290.544195
22  Denali                                      option_payoff      -1919174.0
23  Denali                                   ceding_allowance       49.799115
24  Denali                          refunded_ceding_allowance             0.0
25  Denali                         increase_due_to_prem_bonus        3082.998
26  Denali                        increase_due_fixed_interest  -215961.384386
27   Teton                                   internalreissues               0
28   Teton                                     fullsurrenders         2151146
29   Teton                                 partialwithdrawals         1082416
30   Teton                                 cancellationamount           23080
31   Teton                                     rmdwithdrawals          320675
32   Teton                                   otherwithdrawals               0
33   Teton                                lifetimewithdrawals               0
34   Teton                                           homecare            1788
35   Teton                                        nursinghome           51432
36   Teton                                    terminalillness               0
37   Teton                                wellnesswithdrawals               0
38   Teton     surrendercharges_includesmvaandbonusrecapture_         -371839
39   Teton                                       premiumtaxes               0
40   Teton                              gross_initial_premium             0.0
41   Teton                                gross_addtl_premium         842.737
42   Teton                                              death         2259201
43   Teton                            initial_commission_paid         165.105
44   Teton                               commission_recovered       -2658.964
45   Teton                      number_of_contract_issued_acq               2
46   Teton  acq_expense ($100 per policy x #contracts issued)            10.0
47   Teton                                  maintance_expense    18878.223715
48   Teton                                        hedgin_cost    717139.82213
49   Teton                                      option_payoff      -1224445.8
50   Teton                                   ceding_allowance        33.70948
51   Teton                          refunded_ceding_allowance       712.61992
52   Teton                         increase_due_to_prem_bonus          67.419
53   Teton                        increase_due_fixed_interest    -95231.18644

In [124]:

# Add directory containing LDTI.py
sys.path.append('../actuarial-pipelines/ldti/')

# Import the function
from LDTI import main_query_run

# Trigger the AVRF analysis
main_query_run("SILAC")

Starting LDTI run for : SILAC

    WITH
    min_set_month AS (
      SELECT
      distinct
        policynumber,
        MIN(set_month) AS first_set_month,
        MIN(LEFT(reported_date,4)) as report_year,
      FROM `denali.policy`
      WHERE policynumber like 'D%'
      GROUP BY policynumber
    ),
    inforce_list as (
      select sv.set_month, LEFT(p.reported_date,4) as report_year, count(distinct sv.policynumber) as ct_inforce from `denali.seriatim_values` sv
      JOIN `denali.policy` p ON p.policynumber = sv.policynumber AND sv.set_month = p.set_month and sv.creditstrategy = p.creditstrategy
      WHERE sv.policynumber like 'D%' and totalpolicyav > 0
      GROUP by sv.set_month, LEFT(p.reported_date,4)
      ORDER by sv.set_month, report_year
    )

    SELECT
      i.set_month,
      CAST(i.report_year as INT64) as report_year,
      i.ct_inforce,
      COUNT(m.policynumber) AS new_issued_policies
    FROM inforce_list i
    LEFT JOIN min_set_month m
      ON m.first_set_month = i.set_month AND m.report_year = i.report_year
    GROUP BY i.set_month, i.report_year, i.ct_inforce
    ORDER BY i.set_month, i.report_year;



        WITH total_av_split AS (
            SELECT DISTINCT
                p.policynumber,
                totalpolicyav,
                p.plan,
                converge,
                sv.set_month
            FROM `denali.seriatim_values` sv
            JOIN `denali.policy` p
                ON sv.policynumber = p.policynumber
               AND p.set_month = sv.set_month
            WHERE p.set_month >= "202401"
              AND p.policynumber LIKE 'D%'
        )
        SELECT
          set_month,
          plan,
          SUM(totalpolicyav * converge) AS net_av
        FROM total_av_split
        GROUP BY set_month, plan
        ORDER BY set_month, plan;

[['202007', 2020, 126, 126], ['202008', 2020, 470, 347], ['202009', 2020, 1033, 566], ['202010', 2020, 1646, 620], ['202011', 2020, 2436, 792], ['202012', 2020, 3431, 1007], ['202101', 2020, 3411, 0], ['202101', 2021, 787, 790], ['202102', 2020, 3404, 0], ['202102', 2021, 1617, 840], ['202103', 2020, 3400, 0], ['202103', 2021, 2904, 1298], ['202104', 2020, 3395, 0], ['202104', 2021, 3948, 1061], ['202105', 2020, 3392, 0], ['202105', 2021, 5100, 1169], ['202106', 2020, 3390, 0], ['202106', 2021, 6711, 1631], ['202107', 2020, 3387, 0], ['202107', 2021, 8099, 1416], ['202108', 2020, 3375, 0], ['202108', 2021, 9400, 1337], ['202109', 2020, 3374, 0], ['202109', 2021, 11078, 1698], ['202110', 2020, 3367, 0], ['202110', 2021, 12372, 1319], ['202111', 2020, 3362, 0], ['202111', 2021, 13691, 1340], ['202112', 2020, 3360, 0], ['202112', 2021, 15007, 1347], ['202201', 2020, 3348, 0], ['202201', 2021, 14978, 0], ['202201', 2022, 1204, 1206], ['202202', 2020, 3341, 0], ['202202', 2021, 14960, 0], ['202202', 2022, 2341, 1147], ['202203', 2020, 3329, 0], ['202203', 2021, 14940, 0], ['202203', 2022, 3948, 1625], ['202204', 2020, 3326, 0], ['202204', 2021, 14916, 0], ['202204', 2022, 5103, 1192], ['202205', 2020, 3315, 0], ['202205', 2021, 14881, 0], ['202205', 2022, 6105, 1023], ['202206', 2020, 3308, 0], ['202206', 2021, 14858, 0], ['202206', 2022, 7213, 1126], ['202207', 2020, 3300, 0], ['202207', 2021, 14838, 0], ['202207', 2022, 8013, 819], ['202208', 2020, 3285, 0], ['202208', 2021, 14795, 0], ['202208', 2022, 9036, 1048], ['202209', 2020, 3278, 0], ['202209', 2021, 14762, 0], ['202209', 2022, 9759, 747], ['202210', 2020, 3270, 0], ['202210', 2021, 14735, 0], ['202210', 2022, 10404, 672], ['202211', 2020, 3260, 0], ['202211', 2021, 14711, 0], ['202211', 2022, 11265, 879], ['202212', 2020, 3251, 0], ['202212', 2021, 14681, 0], ['202212', 2022, 11797, 551], ['202301', 2020, 3241, 0], ['202301', 2021, 14657, 0], ['202301', 2022, 11783, 0], ['202301', 2023, 506, 511], ['202302', 2020, 3231, 0], ['202302', 2021, 14607, 0], ['202302', 2022, 11768, 0], ['202302', 2023, 1067, 565], ['202303', 2020, 3216, 0], ['202303', 2021, 14551, 0], ['202303', 2022, 11743, 0], ['202303', 2023, 1891, 836], ['202304', 2020, 3203, 0], ['202304', 2021, 14496, 0], ['202304', 2022, 11719, 0], ['202304', 2023, 2615, 729], ['202305', 2020, 3198, 0], ['202305', 2021, 14443, 0], ['202305', 2022, 11691, 0], ['202305', 2023, 3483, 881], ['202306', 2020, 3187, 0], ['202306', 2021, 14396, 0], ['202306', 2022, 11659, 0], ['202306', 2023, 3474, 2], ['202307', 2020, 3175, 0], ['202307', 2021, 14330, 0], ['202307', 2022, 11630, 0], ['202307', 2023, 3473, 0], ['202308', 2020, 3163, 0], ['202308', 2021, 14263, 0], ['202308', 2022, 11592, 0], ['202308', 2023, 3465, 0], ['202309', 2020, 3146, 0], ['202309', 2021, 14227, 0], ['202309', 2022, 11562, 0], ['202309', 2023, 3463, 1], ['202310', 2020, 3138, 0], ['202310', 2021, 14158, 0], ['202310', 2022, 11537, 0], ['202310', 2023, 3461, 0], ['202311', 2020, 3128, 0], ['202311', 2021, 14099, 0], ['202311', 2022, 11505, 0], ['202311', 2023, 3455, 0], ['202312', 2020, 3106, 0], ['202312', 2021, 14024, 0], ['202312', 2022, 11478, 0], ['202312', 2023, 3452, 2], ['202401', 2020, 3092, 0], ['202401', 2021, 13950, 0], ['202401', 2022, 11449, 0], ['202401', 2023, 3449, 0], ['202402', 2020, 3080, 0], ['202402', 2021, 13879, 0], ['202402', 2022, 11413, 0], ['202402', 2023, 3445, 0], ['202403', 2020, 3057, 0], ['202403', 2021, 13778, 0], ['202403', 2022, 11360, 0], ['202403', 2023, 3437, 0], ['202404', 2020, 3038, 0], ['202404', 2021, 13697, 0], ['202404', 2022, 11309, 0], ['202404', 2023, 3430, 0], ['202404', 2024, 2, 2], ['202405', 2020, 3023, 0], ['202405', 2021, 13590, 0], ['202405', 2022, 11265, 0], ['202405', 2023, 3422, 0], ['202405', 2024, 2, 0], ['202406', 2020, 3013, 0], ['202406', 2021, 13489, 0], ['202406', 2022, 11206, 0], ['202406', 2023, 3415, 0], ['202406', 2024, 2, 0], ['202407', 2020, 3001, 0], ['202407', 2021, 13395, 0], ['202407', 2022, 11157, 0], ['202407', 2023, 3407, 0], ['202407', 2024, 2, 0], ['202408', 2020, 2984, 0], ['202408', 2021, 13303, 0], ['202408', 2022, 11096, 0], ['202408', 2023, 3399, 0], ['202408', 2024, 2, 0], ['202409', 2020, 2968, 0], ['202409', 2021, 13212, 0], ['202409', 2022, 11014, 0], ['202409', 2023, 3391, 0], ['202409', 2024, 2, 0], ['202410', 2020, 2947, 0], ['202410', 2021, 13100, 0], ['202410', 2022, 10952, 0], ['202410', 2023, 3386, 0], ['202410', 2024, 2, 0], ['202411', 2020, 2935, 0], ['202411', 2021, 13046, 0], ['202411', 2022, 10897, 0], ['202411', 2023, 3382, 0], ['202411', 2024, 2, 0], ['202412', 2020, 2922, 0], ['202412', 2021, 12973, 0], ['202412', 2022, 10845, 0], ['202412', 2023, 3371, 0], ['202412', 2024, 2, 0], ['202501', 2020, 2911, 0], ['202501', 2021, 12902, 0], ['202501', 2022, 10803, 0], ['202501', 2023, 3355, 0], ['202501', 2024, 2, 0], ['202502', 2020, 2895, 0], ['202502', 2021, 12826, 0], ['202502', 2022, 10762, 0], ['202502', 2023, 3345, 0], ['202502', 2024, 2, 0], ['202503', 2020, 2878, 0], ['202503', 2021, 12749, 0], ['202503', 2022, 10713, 0], ['202503', 2023, 3336, 0], ['202503', 2024, 2, 0], ['202504', 2020, 2864, 0], ['202504', 2021, 12667, 0], ['202504', 2022, 10646, 0], ['202504', 2023, 3329, 0], ['202504', 2024, 2, 0], ['202505', 2020, 2853, 0], ['202505', 2021, 12594, 0], ['202505', 2022, 10560, 0], ['202505', 2023, 3322, 0], ['202505', 2024, 2, 0], ['202506', 2020, 2840, 0], ['202506', 2021, 12461, 0], ['202506', 2022, 10464, 0], ['202506', 2023, 3311, 0], ['202506', 2024, 2, 0], ['202507', 2020, 2829, 0], ['202507', 2021, 12371, 0], ['202507', 2022, 10389, 0], ['202507', 2023, 3303, 0], ['202507', 2024, 2, 0], ['202508', 2020, 2815, 0], ['202508', 2021, 12269, 0], ['202508', 2022, 10319, 0], ['202508', 2023, 3290, 0], ['202508', 2024, 2, 0], ['202509', 2020, 2806, 0], ['202509', 2021, 12163, 0], ['202509', 2022, 10232, 0], ['202509', 2023, 3280, 0], ['202509', 2024, 2, 0], ['202510', 2020, 2790, 0], ['202510', 2021, 12034, 0], ['202510', 2022, 10124, 0], ['202510', 2023, 3272, 0], ['202510', 2024, 2, 0], ['202511', 2020, 2781, 0], ['202511', 2021, 11955, 0], ['202511', 2022, 10056, 0], ['202511', 2023, 3263, 0], ['202511', 2024, 2, 0], ['202512', 2020, 2764, 0], ['202512', 2021, 11893, 0], ['202512', 2022, 9998, 0], ['202512', 2023, 3258, 0], ['202512', 2024, 2, 0], ['202601', 2020, 2750, 0], ['202601', 2021, 11804, 0], ['202601', 2022, 9933, 0], ['202601', 2023, 3247, 0], ['202601', 2024, 2, 0], ['202602', 2020, 2737, 0], ['202602', 2021, 11725, 0], ['202602', 2022, 9863, 0], ['202602', 2023, 3237, 0], ['202602', 2024, 2, 0], ['202603', 2020, 2717, 0], ['202603', 2021, 11641, 0], ['202603', 2022, 9802, 0], ['202603', 2023, 3225, 0], ['202603', 2024, 2, 0]]
Data exported successfully : Results/LDTI/silac ldti result_D%

    WITH
    min_set_month AS (
      SELECT
      distinct
        policynumber,
        MIN(set_month) AS first_set_month,
        MIN(LEFT(reported_date,4)) as report_year,
      FROM `denali.policy`
      WHERE policynumber like 'T%'
      GROUP BY policynumber
    ),
    inforce_list as (
      select sv.set_month, LEFT(p.reported_date,4) as report_year, count(distinct sv.policynumber) as ct_inforce from `denali.seriatim_values` sv
      JOIN `denali.policy` p ON p.policynumber = sv.policynumber AND sv.set_month = p.set_month and sv.creditstrategy = p.creditstrategy
      WHERE sv.policynumber like 'T%' and totalpolicyav > 0
      GROUP by sv.set_month, LEFT(p.reported_date,4)
      ORDER by sv.set_month, report_year
    )

    SELECT
      i.set_month,
      CAST(i.report_year as INT64) as report_year,
      i.ct_inforce,
      COUNT(m.policynumber) AS new_issued_policies
    FROM inforce_list i
    LEFT JOIN min_set_month m
      ON m.first_set_month = i.set_month AND m.report_year = i.report_year
    GROUP BY i.set_month, i.report_year, i.ct_inforce
    ORDER BY i.set_month, i.report_year;



        WITH total_av_split AS (
            SELECT DISTINCT
                p.policynumber,
                totalpolicyav,
                p.plan,
                converge,
                sv.set_month
            FROM `denali.seriatim_values` sv
            JOIN `denali.policy` p
                ON sv.policynumber = p.policynumber
               AND p.set_month = sv.set_month
            WHERE p.set_month >= "202401"
              AND p.policynumber LIKE 'T%'
        )
        SELECT
          set_month,
          plan,
          SUM(totalpolicyav * converge) AS net_av
        FROM total_av_split
        GROUP BY set_month, plan
        ORDER BY set_month, plan;

[['202012', 2020, 1557, 1560], ['202101', 2020, 1555, 0], ['202101', 2021, 1022, 1024], ['202102', 2020, 1552, 0], ['202102', 2021, 1970, 954], ['202103', 2020, 1548, 0], ['202103', 2021, 3328, 1377], ['202104', 2020, 1545, 0], ['202104', 2021, 4366, 1052], ['202105', 2020, 1544, 0], ['202105', 2021, 5286, 933], ['202106', 2020, 1543, 0], ['202106', 2021, 6499, 1227], ['202107', 2020, 1542, 0], ['202107', 2021, 7320, 841], ['202108', 2020, 1540, 0], ['202108', 2021, 8260, 961], ['202109', 2020, 1540, 0], ['202109', 2021, 9330, 1092], ['202110', 2020, 1537, 0], ['202110', 2021, 10143, 831], ['202111', 2020, 1535, 0], ['202111', 2021, 10915, 802], ['202112', 2020, 1535, 0], ['202112', 2021, 11669, 767], ['202201', 2020, 1531, 0], ['202201', 2021, 11649, 0], ['202201', 2022, 657, 659], ['202202', 2020, 1528, 0], ['202202', 2021, 11634, 0], ['202202', 2022, 1340, 684], ['202203', 2020, 1522, 0], ['202203', 2021, 11608, 0], ['202203', 2022, 2260, 928], ['202204', 2020, 1511, 0], ['202204', 2021, 11580, 0], ['202204', 2022, 2928, 687], ['202205', 2020, 1505, 0], ['202205', 2021, 11529, 0], ['202205', 2022, 3598, 684], ['202206', 2020, 1501, 0], ['202206', 2021, 11501, 0], ['202206', 2022, 4261, 677], ['202207', 2020, 1499, 0], ['202207', 2021, 11469, 0], ['202207', 2022, 4891, 640], ['202208', 2020, 1495, 0], ['202208', 2021, 11437, 0], ['202208', 2022, 5582, 711], ['202209', 2020, 1491, 0], ['202209', 2021, 11408, 0], ['202209', 2022, 6047, 481], ['202210', 2020, 1488, 0], ['202210', 2021, 11377, 0], ['202210', 2022, 6526, 497], ['202211', 2020, 1485, 0], ['202211', 2021, 11360, 0], ['202211', 2022, 7085, 571], ['202212', 2020, 1479, 0], ['202212', 2021, 11338, 0], ['202212', 2022, 7485, 412], ['202301', 2020, 1474, 0], ['202301', 2021, 11308, 0], ['202301', 2022, 7472, 0], ['202301', 2023, 389, 392], ['202302', 2020, 1469, 0], ['202302', 2021, 11271, 0], ['202302', 2022, 7452, 0], ['202302', 2023, 758, 378], ['202303', 2020, 1462, 0], ['202303', 2021, 11209, 0], ['202303', 2022, 7424, 0], ['202303', 2023, 1312, 566], ['202304', 2020, 1458, 0], ['202304', 2021, 11165, 0], ['202304', 2022, 7407, 0], ['202304', 2023, 1797, 494], ['202305', 2020, 1452, 0], ['202305', 2021, 11131, 0], ['202305', 2022, 7390, 0], ['202305', 2023, 2362, 579], ['202306', 2020, 1444, 0], ['202306', 2021, 11087, 0], ['202306', 2022, 7371, 0], ['202306', 2023, 2360, 2], ['202307', 2020, 1438, 0], ['202307', 2021, 11054, 0], ['202307', 2022, 7356, 0], ['202307', 2023, 2355, 0], ['202308', 2020, 1428, 0], ['202308', 2021, 11008, 0], ['202308', 2022, 7332, 0], ['202308', 2023, 2352, 0], ['202309', 2020, 1422, 0], ['202309', 2021, 10965, 0], ['202309', 2022, 7309, 0], ['202309', 2023, 2349, 0], ['202310', 2020, 1415, 0], ['202310', 2021, 10915, 0], ['202310', 2022, 7281, 0], ['202310', 2023, 2349, 0], ['202311', 2020, 1407, 0], ['202311', 2021, 10872, 0], ['202311', 2022, 7257, 0], ['202311', 2023, 2349, 0], ['202312', 2020, 1400, 0], ['202312', 2021, 10809, 0], ['202312', 2022, 7226, 0], ['202312', 2023, 2344, 0], ['202401', 2020, 1397, 0], ['202401', 2021, 10766, 0], ['202401', 2022, 7200, 0], ['202401', 2023, 2341, 0], ['202402', 2020, 1392, 0], ['202402', 2021, 10712, 0], ['202402', 2022, 7175, 0], ['202402', 2023, 2333, 0], ['202403', 2020, 1360, 0], ['202403', 2021, 10242, 0], ['202403', 2022, 6722, 0], ['202403', 2023, 2279, 0], ['202404', 2020, 1353, 0], ['202404', 2021, 10180, 0], ['202404', 2022, 6702, 0], ['202404', 2023, 2274, 0], ['202405', 2020, 1366, 0], ['202405', 2021, 10525, 0], ['202405', 2022, 7071, 0], ['202405', 2023, 2314, 0], ['202406', 2020, 1359, 0], ['202406', 2021, 10461, 0], ['202406', 2022, 7040, 0], ['202406', 2023, 2308, 0], ['202406', 2024, 2, 2], ['202407', 2020, 1352, 0], ['202407', 2021, 10395, 0], ['202407', 2022, 7002, 0], ['202407', 2023, 2303, 0], ['202407', 2024, 4, 2], ['202408', 2020, 1338, 0], ['202408', 2021, 10319, 0], ['202408', 2022, 6958, 0], ['202408', 2023, 2294, 0], ['202408', 2024, 4, 0], ['202409', 2020, 1324, 0], ['202409', 2021, 10242, 0], ['202409', 2022, 6918, 0], ['202409', 2023, 2289, 0], ['202409', 2024, 4, 0], ['202410', 2020, 1318, 0], ['202410', 2021, 10152, 0], ['202410', 2022, 6853, 0], ['202410', 2023, 2277, 0], ['202410', 2024, 4, 0], ['202411', 2020, 1311, 0], ['202411', 2021, 10098, 0], ['202411', 2022, 6823, 0], ['202411', 2023, 2265, 0], ['202411', 2024, 6, 2], ['202412', 2020, 1303, 0], ['202412', 2021, 10038, 0], ['202412', 2022, 6782, 0], ['202412', 2023, 2260, 0], ['202412', 2024, 6, 0], ['202501', 2020, 1298, 0], ['202501', 2021, 9981, 0], ['202501', 2022, 6747, 0], ['202501', 2023, 2251, 0], ['202501', 2024, 6, 0], ['202502', 2020, 1290, 0], ['202502', 2021, 9929, 0], ['202502', 2022, 6719, 0], ['202502', 2023, 2245, 0], ['202502', 2024, 6, 0], ['202502', 2025, 2, 2], ['202503', 2020, 1278, 0], ['202503', 2021, 9855, 0], ['202503', 2022, 6681, 0], ['202503', 2023, 2234, 0], ['202503', 2024, 6, 0], ['202503', 2025, 2, 0], ['202504', 2020, 1271, 0], ['202504', 2021, 9778, 0], ['202504', 2022, 6604, 0], ['202504', 2023, 2227, 0], ['202504', 2024, 6, 0], ['202504', 2025, 2, 0], ['202505', 2020, 1262, 0], ['202505', 2021, 9681, 0], ['202505', 2022, 6535, 0], ['202505', 2023, 2219, 0], ['202505', 2024, 6, 0], ['202505', 2025, 2, 0], ['202506', 2020, 1254, 0], ['202506', 2021, 9570, 0], ['202506', 2022, 6459, 0], ['202506', 2023, 2207, 0], ['202506', 2024, 6, 0], ['202506', 2025, 1, 0], ['202507', 2020, 1245, 0], ['202507', 2021, 9472, 0], ['202507', 2022, 6409, 0], ['202507', 2023, 2190, 0], ['202507', 2024, 6, 0], ['202507', 2025, 1, 0], ['202508', 2020, 1237, 0], ['202508', 2021, 9385, 0], ['202508', 2022, 6347, 0], ['202508', 2023, 2174, 0], ['202508', 2024, 6, 0], ['202508', 2025, 1, 0], ['202509', 2020, 1232, 0], ['202509', 2021, 9277, 0], ['202509', 2022, 6286, 0], ['202509', 2023, 2156, 0], ['202509', 2024, 6, 0], ['202509', 2025, 1, 0], ['202510', 2020, 1220, 0], ['202510', 2021, 9163, 0], ['202510', 2022, 6208, 0], ['202510', 2023, 2145, 0], ['202510', 2024, 6, 0], ['202510', 2025, 1, 0], ['202511', 2020, 1216, 0], ['202511', 2021, 9078, 0], ['202511', 2022, 6157, 0], ['202511', 2023, 2140, 0], ['202511', 2024, 6, 0], ['202511', 2025, 1, 0], ['202512', 2020, 1203, 0], ['202512', 2021, 9019, 0], ['202512', 2022, 6090, 0], ['202512', 2023, 2129, 0], ['202512', 2024, 6, 0], ['202512', 2025, 1, 0], ['202601', 2020, 1189, 0], ['202601', 2021, 8936, 0], ['202601', 2022, 6046, 0], ['202601', 2023, 2112, 0], ['202601', 2024, 6, 0], ['202601', 2025, 1, 0], ['202601', 2026, 2, 2], ['202602', 2020, 1177, 0], ['202602', 2021, 8853, 0], ['202602', 2022, 5999, 0], ['202602', 2023, 2099, 0], ['202602', 2024, 6, 0], ['202602', 2025, 1, 0], ['202602', 2026, 2, 0], ['202603', 2020, 1168, 0], ['202603', 2021, 8790, 0], ['202603', 2022, 5946, 0], ['202603', 2023, 2085, 0], ['202603', 2024, 6, 0], ['202603', 2025, 1, 0], ['202603', 2026, 2, 0]]
Data exported successfully : Results/LDTI/silac ldti result_T%